backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "static/uploads" # Media files will be stored in the repo under images/uploads

collections:
  # Jobs
  - name: "jobs"
    label: "Jobs"
    label_singular: "Job"
    description: "This is where current openings live. You can list the position, locations and type of work."
    folder: "/_collections/jobs"
    create: true
    slug: "{{fields.name}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Type", name: "type", widget: "string"}
  
  # Equipment
  - name: "equipment"
    label: "Equipment for sale"
    label_singular: "listing"
    description: "Here you can list equipment that is for sale, you can upload an image to be displayed, a name, price, and a description."
    folder: "/_collections/equipment"
    create: true
    slug: "{{fields.name}}"
    media_folder: /static/uploads/equipment
    summary: "{{fields.name}} - {{fields.price}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Price", name: "price", widget: "string", default: "$1000"}
      - {label: "Description", name: "desc", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
  
  # Projects
  # - name: "projects"
  #   label: "Projects"
  #   label_singular: "Project"
  #   description: "Structured like a blog, this is the most complicated CMS collection. They contain a large number of properties that you can fill out and then a body field. This is the bulk of the information that is displayed on the page when users want to read about a specific project."
  #   folder: "/_collections/projects"
  #   create: true
  #   slug: "{{fields.name}}"
  #   media_folder: /static/uploads
  #   fields:
  #     - {label: "Name", name: "name", widget: "string"}
  #     - {label: "Project Location", name: "location", widget: "string"}
  #     - {label: "Person of Interest", name: "person", widget: "string"}
  #     - {label: "Date of Project", name: "date", widget: "date", format 'MMM YYYY'}
  #     - {label: "Featured Image", name: "featImage", widget: "image", allow_multiple: false}
  #     - {label: "Other Image", name: "images", widget: "image", allow_multiple: true}
  #     - {label: "Summary Text", name: "summary", widget: "string"}
  #     - {label: "Body", name: "body", widget: "markdown"}
  
  # Team
  - name: "teamImages"
    label: "Team Images"
    label_singular: "Team Image"
    description: "Your team images live here. Upload or remove images from the slideshow on the about page."
    folder: "/_collections/team"
    create: true
    media_folder: /static/uploads/team
    fields:
      - {label: "Image", name: "image", widget: "image"}
  # Projects
  - name: "projects"
    label: "Example Projects"
    label_singular: "Project"
    description: "Your example projects live here. Upload or remove images and summaries from the slideshow on the home page."
    folder: "/_collections/projects"
    create: true
    media_folder: /static/uploads/projects
    fields:
      - {label: "Project Image", name: "image", widget: "image"}
      - {label: "Summary", name: "summary", widget: "string"}
  # Services
  - name: "services"
    label: "Services"
    label_singular: "Service"
    description: "These services are displayed on both the homepage and service page. I have included a set of icons that can be used to add visual appeal to the different services you offer. These icons can be added to by uploading other SVG files."
    folder: "/_collections/services"
    create: true
    slug: "{{fields.name}}"
    media_folder: /static/uploads/serviceIcon
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Summary", name: "summary", widget: "string"}
      - {label: "Icon", name: "icon", widget: "image"}
      - {label: "Homepage?", name: "homepageVisible", widget: "boolean"}
    view_filters:
      - label: "Included on the homepage"
        field: homepageVisible
        pattern: true

  # Hero Images
  - name: "heroicImages"
    label: "Hero Images"
    label_singular: "Image"
    description: "This collection manages the homepage slideshow."
    folder: "/_collections/heroicImages"
    create: true
    media_folder: /static/uploads/
    fields:
      - {label: "Image", name: "image", widget: "image"}

  # # Testimonials
  # - name: "testimonials"
  #   label: "Testimonials"
  #   label_singular: "Testimonial"
  #   description: "Upload testimonials here to have them included on the homepage."
  #   folder: "/_collections/testimonials"
  #   create: true
  #   slug: "{{fields.name}}"
  #   fields:
  #     - {label: "Name", name: "name", widget: "string"}
  #     - {label: "Title or Job", name: "title", widget: "string"}
  #     - {label: "Testimonial", name: "testimonial", widget: "string"}
