backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "static/uploads" # Media files will be stored in the repo under images/uploads

collections:
  # Our blog posts
  # - name: "blog" # Used in routes, e.g., /admin/collections/blog
  #   label: "Post" # Used in the UI
  #   folder: "posts" # The path to the folder where the documents are stored
  #   create: true # Allow users to create new documents in this collection
  #   slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  #   fields: # The fields for each document, usually in front matter
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Publish Date", name: "date", widget: "datetime" }
  #     - label: "Post Author"
  #       name: "author"
  #       widget: "relation"
  #       collection: "authors"
  #       searchFields: ["name", "github"]
  #       valueField: "name"
  #     - { label: "Summary", name: "summary", widget: "text" }
  #     - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
  #     - { label: "Body", name: "body", widget: "markdown" }
  # # Our pages e.g. About
  # - name: "pages"
  #   label: "Page"
  #   folder: "pages"
  #   create: false # Change to true to allow editors to create new pages
  #   slug: "{{slug}}"
  #   fields:
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Publish Date", name: "date", widget: "datetime" }
  #     - { label: "Permalink", name: "permalink", widget: "string" }
  #     - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
  #       name: "eleventyNavigation"
  #       widget: "object"
  #       fields:
  #         - { label: "Key", name: "key", widget: "string" }
  #         - { label: "Order", name: "order", widget: "number", default: 0 }
  #     - { label: "Body", name: "body", widget: "markdown" }
  
  # Jobs
  - name: "jobs"
    label: "Jobs"
    folder: "/_collections/jobs"
    create: true
    slug: "{{fields.name}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Type", name: "type", widget: "string"}
  
  # Equipment
  - name: "equipment"
    label: "Equipment for sale"
    folder: "/_collections/equipment"
    create: true
    slug: "{{fields.name}}"
    media_folder: /static/uploads/equipment
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Price", name: "price", widget: "string", default: "$1000"}
      - {label: "Description", name: "desc", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
  
  # Projects
  - name: "projects"
    label: "Projects"
    folder: "/_collections/projects"
    create: true
    slug: "{{fields.name}}"
    media_folder: /static/uploads/projects
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Project Location", name: "location", widget: "string"}
      - {label: "Person of Interest", name: "person", widget: "string"}
      - {label: "Date of Project", name: "date", widget: "date", format 'MMM YYYY'}
      - {label: "Featured Image", name: "featImage", widget: "image"}
      - {label: "Other Image", name: "images", widget: "image"}
      - {label: "Summary Text", name: "summary", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  
  # Team
  - name: "Team"
    label: "Team"
    folder: "/_collections/team"
    create: true
    slug: "{{fields.name}}"
    media_folder: /static/uploads/team
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Role", name: "role", widget: "string"}
      - {label: "Description", name: "desc", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}

  # Services
  - name: "Services"
    label: "Services"
    folder: "/_collections/services"
    create: true
    slug: "{{fields.name}}"
    media_folder: /static/uploads/serviceIcon
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Summary", name: "summary", widget: "string"}
      - {label: "Icon", name: "icon", widget: "image"}