backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "static/uploads" # Media files will be stored in the repo under images/uploads

collections:
  # Jobs
  - name: "jobs"
    label: "Jobs"
    folder: "/_collections/jobs"
    create: true
    slug: "{{fields.name}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Type", name: "type", widget: "string"}
  
  # Equipment
  - name: "equipment"
    label: "Equipment for sale"
    folder: "/_collections/equipment"
    create: true
    slug: "{{fields.name}}"
    media_folder: /static/uploads/equipment
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Price", name: "price", widget: "string", default: "$1000"}
      - {label: "Description", name: "desc", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
  
  # Projects
  - name: "projects"
    label: "Projects"
    folder: "/_collections/projects"
    create: true
    slug: "{{fields.name}}"
    media_folder: /static/uploads
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Project Location", name: "location", widget: "string"}
      - {label: "Person of Interest", name: "person", widget: "string"}
      - {label: "Date of Project", name: "date", widget: "date", format 'MMM YYYY'}
      - {label: "Featured Image", name: "featImage", widget: "image"}
      - {label: "Other Image", name: "images", widget: "image", allow_multiple: true}
      - {label: "Summary Text", name: "summary", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  
  # Team
  - name: "team"
    label: "Team"
    folder: "/_collections/team"
    create: true
    slug: "{{fields.name}}"
    media_folder: /static/uploads/team
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Role", name: "role", widget: "string"}
      - {label: "Description", name: "desc", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}

  # Services
  - name: "services"
    label: "Services"
    folder: "/_collections/services"
    create: true
    slug: "{{fields.name}}"
    media_folder: /static/uploads/serviceIcon
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Summary", name: "summary", widget: "string"}
      - {label: "Icon", name: "icon", widget: "image"}
      - {label: "Homepage?", name: "homepageVisible", widget: "boolean"}

  # Hero Images
  - name: "heroicImages"
    label: "Hero Images"
    folder: "/_collections/heroicImages"
    create: true
    media_folder: /static/uploads/
    summary: {{image}}
    fields:
      - {label: "Image", name: "image", widget: "image"}

  # Testimonials
  - name: "testimonials"
    label: "Testimonials"
    folder: "/_collections/testimonials"
    create: true
    slug: "{{fields.name}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Title or Job", name: "title", widget: "string"}
      - {label: "Testimonial", name: "testimonial", widget: "string"}
